"""
Multilingual exercise catalog from free-exercise-db (873 exercises, stretching excluded).
Group indices match MUSCLE_GROUPS in translations.py:
  0 Chest, 1 Back, 2 Shoulders, 3 Biceps/Forearms, 4 Triceps, 5 Abs,
  6 Quads, 7 Hamstrings, 8 Glutes/Abductors/Adductors, 9 Calves, 10 Cardio/Plyometrics
Source: https://github.com/yuhonas/free-exercise-db (745 exercises after filtering)
"""

_EN: list[list[str]] = [
    # 0 Chest (69)
    ['Alternating Floor Press', 'Around The Worlds', 'Barbell Bench Press - Medium Grip',
     'Barbell Guillotine Bench Press', 'Barbell Incline Bench Press - Medium Grip',
     'Bench Press - With Bands', 'Bent-Arm Dumbbell Pullover', 'Bodyweight Flyes',
     'Butterfly', 'Cable Chest Press', 'Cable Crossover', 'Cable Iron Cross',
     'Chain Press', 'Clock Push-Up', 'Cross Over - With Bands',
     'Decline Barbell Bench Press', 'Decline Dumbbell Bench Press', 'Decline Dumbbell Flyes',
     'Decline Push-Up', 'Decline Smith Press', 'Dips - Chest Version',
     'Dumbbell Bench Press', 'Dumbbell Bench Press with Neutral Grip', 'Dumbbell Flyes',
     'Extended Range One-Arm Kettlebell Floor Press', 'Flat Bench Cable Flyes',
     'Forward Drag with Press', 'Front Raise And Pullover',
     'Hammer Grip Incline DB Bench Press', 'Incline Cable Chest Press',
     'Incline Cable Flye', 'Incline Dumbbell Bench With Palms Facing In',
     'Incline Dumbbell Flyes', 'Incline Dumbbell Flyes - With A Twist',
     'Incline Dumbbell Press', 'Incline Push-Up', 'Incline Push-Up Medium',
     'Incline Push-Up Reverse Grip', 'Incline Push-Up Wide', 'Isometric Wipers',
     'Leg-Over Floor Press', 'Leverage Chest Press', 'Leverage Decline Chest Press',
     'Leverage Incline Chest Press', 'Low Cable Crossover', 'Machine Bench Press',
     'Neck Press', 'One Arm Dumbbell Bench Press', 'One-Arm Flat Bench Dumbbell Flye',
     'One-Arm Kettlebell Floor Press', 'Plyo Kettlebell Pushups', 'Push Up to Side Plank',
     'Push-Up Wide', 'Push-Ups With Feet Elevated', 'Push-Ups With Feet On An Exercise Ball',
     'Pushups', 'Pushups (Close and Wide Hand Positions)', 'Single-Arm Cable Crossover',
     'Single-Arm Push-Up', 'Smith Machine Bench Press', 'Smith Machine Decline Press',
     'Smith Machine Incline Bench Press', 'Standing Cable Chest Press',
     'Straight-Arm Dumbbell Pullover', 'Suspended Push-Up', 'Svend Press',
     'Wide-Grip Barbell Bench Press', 'Wide-Grip Decline Barbell Bench Press',
     'Wide-Grip Decline Barbell Pullover'],

    # 1 Back (90)
    ['Alternating Kettlebell Row', 'Alternating Renegade Row', 'Atlas Stone Trainer',
     'Atlas Stones', 'Axle Deadlift', 'Band Assisted Pull-Up', 'Barbell Deadlift',
     'Barbell Shrug', 'Barbell Shrug Behind The Back', 'Bent Over Barbell Row',
     'Bent Over One-Arm Long Bar Row', 'Bent Over Two-Arm Long Bar Row',
     'Bent Over Two-Dumbbell Row', 'Bent Over Two-Dumbbell Row With Palms In',
     'Bent-Arm Barbell Pullover', 'Bodyweight Mid Row', 'Cable Incline Pushdown',
     'Cable Shrugs', 'Calf-Machine Shoulder Shrug', 'Chin-Up', 'Clean Shrug',
     'Close-Grip Front Lat Pulldown', 'Deadlift with Bands', 'Deadlift with Chains',
     'Deficit Deadlift', 'Dumbbell Incline Row', 'Dumbbell Shrug',
     'Elevated Cable Rows', 'Full Range-Of-Motion Lat Pulldown',
     'Gironda Sternum Chins', 'Hyperextensions (Back Extensions)',
     'Hyperextensions With No Hyperextension Bench', 'Incline Bench Pull',
     'Inverted Row', 'Inverted Row with Straps', 'Keg Load',
     'Kettlebell Sumo High Pull', 'Kipping Muscle Up',
     'Kneeling High Pulley Row', 'Kneeling Single-Arm High Pulley Row',
     'Leverage High Row', 'Leverage Iso Row', 'Leverage Shrug', 'London Bridges',
     'Lying Cambered Barbell Row', 'Lying T-Bar Row', 'Middle Back Shrug',
     'Mixed Grip Chin', 'Muscle Up', 'One Arm Chin-Up', 'One Arm Lat Pulldown',
     'One-Arm Dumbbell Row', 'One-Arm Kettlebell Row', 'One-Arm Long Bar Row',
     'Pullups', 'Rack Pull with Bands', 'Rack Pulls', 'Reverse Band Deadlift',
     'Reverse Grip Bent-Over Rows', 'Rocky Pull-Ups/Pulldowns', 'Rope Climb',
     'Rope Straight-Arm Pulldown', 'Scapular Pull-Up', 'Seated Cable Rows',
     'Seated Good Mornings', 'Seated One-arm Cable Pulley Rows', 'Shotgun Row',
     'Side To Side Chins', 'Sled Row', 'Smith Machine Behind the Back Shrug',
     'Smith Machine Bent Over Row', 'Smith Machine Upright Row', 'Snatch Shrug',
     'Standing Dumbbell Upright Row', 'Stiff Leg Barbell Good Morning',
     'Straight Bar Bench Mid Rows', 'Straight-Arm Pulldown', 'Suspended Row',
     'T-Bar Row with Handle', 'Two-Arm Kettlebell Row', 'Underhand Cable Pulldowns',
     'Upright Cable Row', 'Upright Row - With Bands', 'V-Bar Pulldown',
     'V-Bar Pullup', 'Weighted Ball Hyperextension', 'Weighted Pull Ups',
     'Wide-Grip Lat Pulldown', 'Wide-Grip Pulldown Behind The Neck',
     'Wide-Grip Rear Pull-Up'],

    # 2 Shoulders (112)
    ['Alternating Cable Shoulder Press', 'Alternating Deltoid Raise',
     'Alternating Kettlebell Press', 'Anti-Gravity Press', 'Arnold Dumbbell Press',
     'Back Flyes - With Bands', 'Band Pull Apart', 'Barbell Incline Shoulder Raise',
     'Barbell Rear Delt Row', 'Barbell Shoulder Press', 'Battling Ropes',
     'Bent Over Dumbbell Rear Delt Raise With Head On Bench',
     'Bent Over Low-Pulley Side Lateral', 'Bradford/Rocky Presses',
     'Cable Internal Rotation', 'Cable Rear Delt Fly', 'Cable Rope Rear-Delt Rows',
     'Cable Seated Lateral Raise', 'Cable Shoulder Press', 'Car Drivers',
     'Circus Bell', 'Clean and Jerk', 'Clean and Press', 'Crucifix', 'Cuban Press',
     'Double Kettlebell Jerk', 'Double Kettlebell Push Press', 'Double Kettlebell Snatch',
     'Dumbbell Incline Shoulder Raise', 'Dumbbell Lying One-Arm Rear Lateral Raise',
     'Dumbbell Lying Rear Lateral Raise', 'Dumbbell One-Arm Shoulder Press',
     'Dumbbell One-Arm Upright Row', 'Dumbbell Raise', 'Dumbbell Scaption',
     'Dumbbell Shoulder Press', 'External Rotation', 'External Rotation with Band',
     'External Rotation with Cable', 'Face Pull', 'Front Cable Raise',
     'Front Dumbbell Raise', 'Front Incline Dumbbell Raise', 'Front Plate Raise',
     'Front Two-Dumbbell Raise', 'Handstand Push-Ups', 'Internal Rotation with Band',
     'Iron Cross', 'Jerk Balance', 'Kettlebell Arnold Press', 'Kettlebell Pirate Ships',
     'Kettlebell Seated Press', 'Kettlebell Seesaw Press', 'Kettlebell Thruster',
     'Kettlebell Turkish Get-Up (Lunge style)', 'Kettlebell Turkish Get-Up (Squat style)',
     'Landmine Linear Jammer', 'Lateral Raise - With Bands', 'Leverage Shoulder Press',
     'Log Lift', 'Low Pulley Row To Neck', 'Lying One-Arm Lateral Raise',
     'Lying Rear Delt Raise', 'Machine Shoulder (Military) Press',
     'One-Arm Incline Lateral Raise', 'One-Arm Kettlebell Clean and Jerk',
     'One-Arm Kettlebell Jerk', 'One-Arm Kettlebell Military Press To The Side',
     'One-Arm Kettlebell Para Press', 'One-Arm Kettlebell Push Press',
     'One-Arm Kettlebell Snatch', 'One-Arm Kettlebell Split Jerk',
     'One-Arm Kettlebell Split Snatch', 'One-Arm Side Laterals', 'Power Partials',
     'Push Press', 'Push Press - Behind the Neck', 'Rack Delivery', 'Reverse Flyes',
     'Reverse Flyes With External Rotation', 'Reverse Machine Flyes',
     'Seated Barbell Military Press', 'Seated Bent-Over Rear Delt Raise',
     'Seated Cable Shoulder Press', 'Seated Dumbbell Press', 'Seated Side Lateral Raise',
     'See-Saw Press (Alternating Side Press)', 'Shoulder Press - With Bands',
     'Side Lateral Raise', 'Side Laterals to Front Raise', 'Single Dumbbell Raise',
     'Single-Arm Linear Jammer', 'Sled Overhead Backward Walk', 'Sled Reverse Flye',
     'Smith Incline Shoulder Raise', 'Smith Machine One-Arm Upright Row',
     'Smith Machine Overhead Shoulder Press', 'Standing Alternating Dumbbell Press',
     'Standing Barbell Press Behind Neck', 'Standing Bradford Press',
     'Standing Dumbbell Press',
     'Standing Dumbbell Straight-Arm Front Delt Raise Above Head',
     'Standing Front Barbell Raise Over Head', 'Standing Low-Pulley Deltoid Raise',
     'Standing Military Press', 'Standing Palm-In One-Arm Dumbbell Press',
     'Standing Palms-In Dumbbell Press', 'Straight Raises on Incline Bench',
     'Two-Arm Kettlebell Clean', 'Two-Arm Kettlebell Jerk',
     'Two-Arm Kettlebell Military Press', 'Upright Barbell Row'],

    # 3 Biceps / Forearms (73)
    ['Alternate Hammer Curl', 'Alternate Incline Dumbbell Curl', 'Barbell Curl',
     'Barbell Curls Lying Against An Incline',
     'Bottoms-Up Clean From The Hang Position',
     'Cable Hammer Curls - Rope Attachment', 'Cable Preacher Curl', 'Cable Wrist Curl',
     'Close-Grip EZ Bar Curl', 'Close-Grip EZ-Bar Curl with Band',
     'Close-Grip Standing Barbell Curl', 'Concentration Curls', 'Cross Body Hammer Curl',
     'Drag Curl', 'Dumbbell Alternate Bicep Curl', 'Dumbbell Bicep Curl',
     'Dumbbell Lying Pronation', 'Dumbbell Lying Supination',
     'Dumbbell Prone Incline Curl', 'EZ-Bar Curl', "Farmer's Walk", 'Finger Curls',
     'Flexor Incline Dumbbell Curls', 'Hammer Curls', 'High Cable Curls',
     'Incline Dumbbell Curl', 'Incline Hammer Curls', 'Incline Inner Biceps Curl',
     'Lying Cable Curl', 'Lying Close-Grip Bar Curl On High Pulley',
     'Lying High Bench Barbell Curl', 'Lying Supine Dumbbell Curl',
     'Machine Bicep Curl', 'Machine Preacher Curls', 'One Arm Dumbbell Preacher Curl',
     'Overhead Cable Curl', 'Palms-Down Dumbbell Wrist Curl Over A Bench',
     'Palms-Down Wrist Curl Over A Bench', 'Palms-Up Barbell Wrist Curl Over A Bench',
     'Palms-Up Dumbbell Wrist Curl Over A Bench', 'Plate Pinch', 'Preacher Curl',
     'Preacher Hammer Dumbbell Curl', 'Reverse Barbell Curl',
     'Reverse Barbell Preacher Curls', 'Reverse Cable Curl', 'Reverse Plate Curls',
     'Rickshaw Carry', 'Seated Close-Grip Concentration Barbell Curl',
     'Seated Dumbbell Curl', 'Seated Dumbbell Inner Biceps Curl',
     'Seated Dumbbell Palms-Down Wrist Curl', 'Seated Dumbbell Palms-Up Wrist Curl',
     'Seated One-Arm Dumbbell Palms-Down Wrist Curl',
     'Seated One-Arm Dumbbell Palms-Up Wrist Curl', 'Seated Palm-Up Barbell Wrist Curl',
     'Seated Palms-Down Barbell Wrist Curl',
     'Seated Two-Arm Palms-Up Low-Pulley Wrist Curl', 'Spider Curl',
     'Standing Biceps Cable Curl', 'Standing Concentration Curl',
     'Standing Dumbbell Reverse Curl', 'Standing Inner-Biceps Curl',
     'Standing Olympic Plate Hand Squeeze', 'Standing One-Arm Cable Curl',
     'Standing One-Arm Dumbbell Curl Over Incline Bench',
     'Standing Palms-Up Barbell Behind The Back Wrist Curl',
     'Two-Arm Dumbbell Preacher Curl', 'Wide-Grip Standing Barbell Curl',
     'Wrist Roller', 'Wrist Rotations with Straight Bar', 'Zottman Curl',
     'Zottman Preacher Curl'],

    # 4 Triceps (67)
    ['Band Skull Crusher', 'Bench Dips', 'Bench Press - Powerlifting',
     'Bench Press with Chains', 'Board Press', 'Body Tricep Press', 'Body-Up',
     'Cable Incline Triceps Extension', 'Cable Lying Triceps Extension',
     'Cable One Arm Tricep Extension', 'Cable Rope Overhead Triceps Extension',
     'Chain Handle Extension', 'Close-Grip Barbell Bench Press',
     'Close-Grip Dumbbell Press', 'Close-Grip EZ-Bar Press',
     'Close-Grip Push-Up off of a Dumbbell',
     'Decline Close-Grip Bench To Skull Crusher',
     'Decline Dumbbell Triceps Extension', 'Decline EZ Bar Triceps Extension',
     'Dip Machine', 'Dips - Triceps Version', 'Dumbbell Floor Press',
     'Dumbbell One-Arm Triceps Extension', 'Dumbbell Tricep Extension -Pronated Grip',
     'EZ-Bar Skullcrusher', 'Floor Press', 'Floor Press with Chains',
     'Incline Barbell Triceps Extension', 'Incline Push-Up Close-Grip', 'JM Press',
     'Kneeling Cable Triceps Extension', 'Low Cable Triceps Extension',
     'Lying Close-Grip Barbell Triceps Extension Behind The Head',
     'Lying Close-Grip Barbell Triceps Press To Chin',
     'Lying Dumbbell Tricep Extension', 'Lying Triceps Press',
     'Machine Triceps Extension', 'One Arm Floor Press',
     'One Arm Pronated Dumbbell Triceps Extension',
     'One Arm Supinated Dumbbell Triceps Extension', 'Parallel Bar Dip',
     'Pin Presses', 'Push-Ups - Close Triceps Position', 'Reverse Band Bench Press',
     'Reverse Grip Triceps Pushdown', 'Reverse Triceps Bench Press', 'Ring Dips',
     'Seated Bent-Over One-Arm Dumbbell Triceps Extension',
     'Seated Bent-Over Two-Arm Dumbbell Triceps Extension', 'Seated Triceps Press',
     'Sled Overhead Triceps Extension', 'Smith Machine Close-Grip Bench Press',
     'Speed Band Overhead Triceps',
     'Standing Bent-Over One-Arm Dumbbell Triceps Extension',
     'Standing Bent-Over Two-Arm Dumbbell Triceps Extension',
     'Standing Dumbbell Triceps Extension',
     'Standing Low-Pulley One-Arm Triceps Extension',
     'Standing One-Arm Dumbbell Triceps Extension',
     'Standing Overhead Barbell Triceps Extension', 'Standing Towel Triceps Extension',
     'Tate Press', 'Tricep Dumbbell Kickback', 'Triceps Overhead Extension with Rope',
     'Triceps Pushdown', 'Triceps Pushdown - Rope Attachment',
     'Triceps Pushdown - V-Bar Attachment', 'Weighted Bench Dip'],

    # 5 Abs (81)
    ['3/4 Sit-Up', 'Ab Crunch Machine', 'Ab Roller', 'Advanced Kettlebell Windmill',
     'Air Bike', 'Alternate Heel Touchers', 'Barbell Ab Rollout',
     'Barbell Ab Rollout - On Knees', 'Barbell Rollout from Bench', 'Barbell Side Bend',
     'Bent Press', 'Bent-Knee Hip Raise', 'Bosu Ball Cable Crunch With Side Bends',
     'Bottoms Up', 'Butt-Ups', 'Cable Crunch', 'Cable Judo Flip',
     'Cable Reverse Crunch', 'Cable Russian Twists', 'Cable Seated Crunch', 'Cocoons',
     'Cross-Body Crunch', 'Crunch - Hands Overhead', 'Crunch - Legs On Exercise Ball',
     'Crunches', 'Dead Bug', 'Decline Crunch', 'Decline Oblique Crunch',
     'Decline Reverse Crunch', 'Double Kettlebell Windmill', 'Dumbbell Side Bend',
     'Elbow to Knee', 'Exercise Ball Crunch', 'Exercise Ball Pull-In',
     'Flat Bench Leg Pull-In', 'Flat Bench Lying Leg Raise', 'Frog Sit-Ups',
     'Gorilla Chin/Crunch', 'Hanging Leg Raise', 'Hanging Pike', 'Jackknife Sit-Up',
     'Janda Sit-Up', 'Kettlebell Figure 8', 'Kettlebell Pass Between The Legs',
     'Kettlebell Windmill', 'Knee/Hip Raise On Parallel Bars',
     'Kneeling Cable Crunch With Alternating Oblique Twists', "Landmine 180's",
     'Leg Pull-In', 'Oblique Crunches', 'Oblique Crunches - On The Floor',
     'One-Arm High-Pulley Cable Side Bends', 'One-Arm Medicine Ball Slam', 'Otis-Up',
     'Pallof Press', 'Pallof Press With Rotation', 'Plank', 'Plate Twist',
     'Press Sit-Up', 'Reverse Crunch', 'Rope Crunch', 'Russian Twist',
     'Seated Barbell Twist', 'Seated Flat Bench Leg Pull-In', 'Seated Leg Tucks',
     'Side Bridge', 'Side Jackknife', 'Sit-Up', 'Smith Machine Hip Raise',
     'Spell Caster', 'Spider Crawl', 'Standing Cable Lift', 'Standing Cable Wood Chop',
     'Standing Rope Crunch', 'Suspended Fallout', 'Suspended Reverse Crunch',
     'Tuck Crunch', 'Weighted Ball Side Bend', 'Weighted Crunches',
     'Weighted Sit-Ups - With Bands', 'Wind Sprints'],

    # 6 Quadriceps (93)
    ['Backward Drag', 'Barbell Full Squat', 'Barbell Hack Squat', 'Barbell Lunge',
     'Barbell Side Split Squat', 'Barbell Squat', 'Barbell Squat To A Bench',
     'Barbell Step Ups', 'Barbell Walking Lunge', 'Bear Crawl Sled Drags',
     'Bodyweight Squat', 'Bodyweight Walking Lunge', 'Box Squat',
     'Box Squat with Bands', 'Box Squat with Chains', 'Cable Deadlifts',
     'Cable Hip Adduction', 'Car Deadlift', 'Chair Squat', 'Clean Pull',
     'Clean from Blocks', "Conan's Wheel", 'Dumbbell Lunges', 'Dumbbell Rear Lunge',
     'Dumbbell Squat', 'Dumbbell Squat To A Bench', 'Dumbbell Step Ups',
     'Elevated Back Lunge', 'Frankenstein Squat', 'Freehand Jump Squat',
     'Front Barbell Squat', 'Front Barbell Squat To A Bench',
     'Front Squat (Clean Grip)', 'Front Squats With Two Kettlebells', 'Goblet Squat',
     'Hack Squat', 'Hang Clean', 'Hang Clean - Below the Knees',
     'Heaving Snatch Balance', 'Hip Flexion with Band', 'Jefferson Squats',
     'Jerk Dip Squat', 'Kettlebell Pistol Squat', 'Leg Extensions', 'Leg Press',
     'Leverage Deadlift', 'Lunge Sprint', 'Lying Machine Squat',
     'Narrow Stance Hack Squats', 'Narrow Stance Leg Press', 'Narrow Stance Squats',
     'Olympic Squat', 'One Leg Barbell Squat', 'One-Arm Overhead Kettlebell Squats',
     'One-Arm Side Deadlift', 'Overhead Squat', 'Plie Dumbbell Squat', 'Power Jerk',
     'Power Snatch from Blocks', 'Reverse Band Box Squat', 'Reverse Band Power Squat',
     'Rickshaw Deadlift', 'Sandbag Load', 'Single-Leg High Box Squat',
     'Single-Leg Leg Extension', 'Sled Drag - Harness', 'Sled Push',
     'Smith Machine Leg Press', 'Smith Machine Pistol Squat', 'Smith Machine Squat',
     'Smith Single-Leg Split Squat', 'Snatch', 'Snatch Balance', 'Snatch from Blocks',
     'Speed Box Squat', 'Speed Squats', 'Split Clean', 'Split Jerk',
     'Split Squat with Dumbbells', 'Squat Jerk', 'Squat with Bands',
     'Squat with Chains', 'Squat with Plate Movers', 'Squats - With Bands',
     'Suspended Split Squat', 'Tire Flip', 'Trap Bar Deadlift', 'Weighted Jump Squat',
     'Weighted Sissy Squat', 'Weighted Squat', 'Wide Stance Barbell Squat',
     'Yoke Walk', 'Zercher Squats'],

    # 7 Hamstrings (50)
    ['Alternating Hang Clean', 'Ball Leg Curl', 'Band Good Morning',
     'Band Good Morning (Pull Through)', 'Clean', 'Clean Deadlift',
     'Double Kettlebell Alternating Hang Clean', 'Dumbbell Clean',
     'Floor Glute-Ham Raise', 'Glute Ham Raise', 'Good Morning',
     'Good Morning off Pins', 'Hang Snatch', 'Hang Snatch - Below Knees',
     'Hanging Bar Good Morning', 'Kettlebell Dead Clean', 'Kettlebell Hang Clean',
     'Kettlebell One-Legged Deadlift', 'Lunge Pass Through', 'Lying Leg Curls',
     'Muscle Snatch', 'Natural Glute Ham Raise', 'One-Arm Kettlebell Clean',
     'One-Arm Kettlebell Swings', 'One-Arm Open Palm Kettlebell Clean',
     'Open Palm Kettlebell Clean', 'Platform Hamstring Slides', 'Power Clean',
     'Power Clean from Blocks', 'Power Snatch', 'Power Stairs',
     'Prone Manual Hamstring', 'Reverse Band Sumo Deadlift', 'Reverse Hyperextension',
     'Romanian Deadlift', 'Romanian Deadlift from Deficit', 'Seated Band Hamstring Curl',
     'Seated Leg Curl', 'Smith Machine Hang Power Clean',
     'Smith Machine Stiff-Legged Deadlift', 'Snatch Deadlift', 'Snatch Pull',
     'Split Snatch', 'Standing Leg Curl', 'Stiff-Legged Barbell Deadlift',
     'Stiff-Legged Dumbbell Deadlift', 'Sumo Deadlift', 'Sumo Deadlift with Bands',
     'Sumo Deadlift with Chains', 'Wide Stance Stiff Legs'],

    # 8 Glutes / Abductors / Adductors (20)
    ['Band Hip Adductions', 'Barbell Glute Bridge', 'Barbell Hip Thrust',
     'Butt Lift (Bridge)', 'Downward Facing Balance', 'Flutter Kicks',
     'Glute Kickback', 'Hip Extension with Bands', 'Hip Lift with Band',
     'Kneeling Jump Squat', 'Kneeling Squat', 'Leg Lift', 'Monster Walk',
     'One-Legged Cable Kickback', 'Physioball Hip Bridge', 'Pull Through',
     'Single Leg Glute Bridge', 'Step-up with Knee Raise', 'Thigh Abductor',
     'Thigh Adductor'],

    # 9 Calves (15)
    ['Balance Board', 'Barbell Seated Calf Raise', 'Calf Press',
     'Calf Press On The Leg Press Machine', 'Calf Raise On A Dumbbell',
     'Calf Raises - With Bands', 'Donkey Calf Raises',
     'Dumbbell Seated One-Leg Calf Raise', 'Rocking Standing Calf Raise',
     'Seated Calf Raise', 'Smith Machine Calf Raise',
     'Smith Machine Reverse Calf Raises', 'Standing Barbell Calf Raise',
     'Standing Calf Raises', 'Standing Dumbbell Calf Raise'],

    # 10 Cardio / Plyometrics (75)
    ['Alternate Leg Diagonal Bound', 'Backward Medicine Ball Throw', 'Bench Jump',
     'Bench Sprint', 'Bicycling', 'Bicycling, Stationary', 'Box Jump (Multiple Response)',
     'Box Skip', 'Carioca Quick Step', 'Catch and Overhead Throw',
     'Chest Push (multiple response)', 'Chest Push (single response)',
     'Chest Push from 3 point stance', 'Chest Push with Run Release',
     'Depth Jump Leap', 'Double Leg Butt Kick', 'Drop Push', 'Dumbbell Seated Box Jump',
     'Elliptical Trainer', 'Fast Skipping', 'Front Box Jump',
     'Front Cone Hops (or hurdle hops)', 'Heavy Bag Thrust', 'Hurdle Hops',
     'Incline Push-Up Depth Jump', 'Isometric Chest Squeezes', 'Jogging, Treadmill',
     'Knee Tuck Jump', 'Kneeling Arm Drill', 'Lateral Bound', 'Lateral Box Jump',
     'Lateral Cone Hops', 'Linear 3-Part Start Technique',
     'Linear Acceleration Wall Drill', 'Linear Depth Jump', 'Medicine Ball Chest Pass',
     'Medicine Ball Full Twist', 'Medicine Ball Scoop Throw', 'Mountain Climbers',
     'Moving Claw Series', 'Overhead Slam', 'Plyo Push-up', 'Prowler Sprint',
     'Quick Leap', 'Recumbent Bike', 'Return Push from Stance', 'Rocket Jump',
     'Rope Jumping', 'Rowing, Stationary', 'Running, Treadmill', 'Scissors Jump',
     'Side Hop-Sprint', 'Side Standing Long Jump', 'Side to Side Box Shuffle',
     'Single Leg Butt Kick', 'Single Leg Push-off', 'Single-Cone Sprint Drill',
     'Single-Leg Hop Progression', 'Single-Leg Lateral Hop', 'Single-Leg Stride Jump',
     'Skating', 'Sledgehammer Swings', 'Split Jump', 'Stairmaster',
     'Standing Long Jump', 'Standing Two-Arm Overhead Throw', 'Star Jump', 'Step Mill',
     'Stride Jump Crossover', 'Supine Chest Throw', 'Supine One-Arm Overhead Throw',
     'Supine Two-Arm Overhead Throw', 'Trail Running/Walking', 'Vertical Swing',
     'Walking, Treadmill'],
]

_RU: list[list[str]] = [
    # 0 Грудь (69)
    ['Поочерёдный жим лёжа на полу', '«Вокруг света»',
     'Жим штанги лёжа — средний хват', 'Жим штанги лёжа «гильотина»',
     'Жим штанги на наклонной — средний хват', 'Жим лёжа с резиной',
     'Пуловер с гантелью согнутыми руками', 'Разводка с весом тела',
     'Баттерфляй', 'Жим в кроссовере', 'Кроссовер', 'Железный крест в кроссовере',
     'Жим с цепями', 'Отжимания «часовая стрелка»', 'Кроссовер с резиной',
     'Жим штанги на обратном наклоне', 'Жим гантелей на обратном наклоне',
     'Разводка гантелей на обратном наклоне',
     'Отжимания на обратном наклоне', 'Жим в Смите на обратном наклоне',
     'Дипсы (грудь)',
     'Жим гантелей лёжа', 'Жим гантелей лёжа нейтральным хватом', 'Разводка гантелей лёжа',
     'Жим кеттлбела одной рукой лёжа (увеличенная амплитуда)', 'Разводка в кроссовере лёжа',
     'Протяжка с жимом', 'Подъём вперёд и пуловер',
     'Жим гантелей на наклонной нейтральным хватом', 'Жим в кроссовере на наклонной',
     'Разводка в кроссовере на наклонной', 'Жим гантелей на наклонной ладонями внутрь',
     'Разводка гантелей на наклонной', 'Разводка гантелей на наклонной с поворотом',
     'Жим гантелей на наклонной', 'Отжимания на наклонной',
     'Отжимания на наклонной (средние)', 'Отжимания на наклонной обратным хватом',
     'Отжимания на наклонной широким хватом', 'Изометрические стеклоочистители',
     'Жим лёжа на полу с перекидыванием ноги', 'Жим в рычажном тренажёре (грудь)',
     'Жим в рычажном тренажёре на обратном наклоне',
     'Жим в рычажном тренажёре на наклонной', 'Кроссовер с нижнего блока',
     'Жим в тренажёре', 'Жим Гильотина',
     'Жим гантели одной рукой лёжа', 'Разводка одной рукой лёжа',
     'Жим кеттлбела одной рукой лёжа', 'Плиометрические отжимания с кеттлбелом',
     'Отжимание с переходом в боковую планку',
     'Отжимания широким хватом', 'Отжимания с ногами на возвышении',
     'Отжимания с ногами на мяче',
     'Отжимания', 'Отжимания (узкий и широкий хват)', 'Кроссовер одной рукой',
     'Отжимания на одной руке', 'Жим лёжа в Смите',
     'Жим в Смите на обратном наклоне', 'Жим в Смите на наклонной',
     'Жим в кроссовере стоя',
     'Пуловер с гантелью прямыми руками', 'Отжимания в петлях',
     'Жим Свенда',
     'Жим штанги широким хватом', 'Жим штанги на обратном наклоне широким хватом',
     'Пуловер на обратном наклоне широким хватом'],

    # 1 Спина (90)
    ['Поочерёдная тяга кеттлбела', 'Поочерёдная тяга в планке',
     'Тренировка с камнем Атласа', 'Камни Атласа', 'Становая тяга с осью',
     'Подтягивания с резиной', 'Становая тяга со штангой',
     'Шраги со штангой', 'Шраги со штангой за спиной', 'Тяга штанги в наклоне',
     'Тяга длинного грифа одной рукой в наклоне', 'Тяга длинного грифа двумя руками в наклоне',
     'Тяга двух гантелей в наклоне', 'Тяга двух гантелей в наклоне ладонями внутрь',
     'Пуловер со штангой согнутыми руками', 'Горизонтальные подтягивания',
     'Прижимание в кроссовере на наклонной',
     'Шраги в кроссовере', 'Шраги в тренажёре для икр', 'Подтягивания обратным хватом',
     'Шраги в тяге',
     'Тяга верхнего блока узким хватом',
     'Становая тяга с резиной', 'Становая тяга с цепями',
     'Становая тяга с дефицита', 'Тяга гантели на наклонной',
     'Шраги с гантелями',
     'Тяга кроссовера с возвышения', 'Тяга верхнего блока полной амплитудой',
     'Подтягивания Жиронды',
     'Гиперэкстензия', 'Гиперэкстензия без тренажёра',
     'Тяга на наклонной скамье',
     'Горизонтальные подтягивания (перевёрнутая тяга)', 'Горизонтальные подтягивания в петлях',
     'Подъём бочки',
     'Тяга кеттлбела сумо к подбородку', 'Мышечный выход с махом',
     'Тяга верхнего блока стоя на коленях', 'Тяга верхнего блока одной рукой на коленях',
     'Тяга в рычажном тренажёре сверху', 'Изолированная тяга в рычажном тренажёре',
     'Шраги в рычажном тренажёре', '«Лондонские мосты»',
     'Тяга изогнутого грифа лёжа', 'Тяга Т-грифа лёжа',
     'Шраги средней части спины',
     'Подтягивания разным хватом', 'Мышечный выход', 'Подтягивания одной рукой',
     'Тяга верхнего блока одной рукой',
     'Тяга гантели одной рукой', 'Тяга кеттлбела одной рукой',
     'Тяга длинного грифа одной рукой',
     'Подтягивания', 'Тяга с подставок с резиной', 'Тяга с подставок',
     'Становая тяга с резиной снизу',
     'Тяга штанги в наклоне обратным хватом', 'Подтягивания по-Роки',
     'Лазание по канату',
     'Тяга верхнего блока (канат) прямыми руками', 'Подтягивания на лопатках',
     'Горизонтальная тяга в блоке', 'Гудморнинг сидя',
     'Горизонтальная тяга одной рукой', 'Тяга «ружьё»',
     'Подтягивания в стороны', 'Тяга саней',
     'Шраги в Смите за спиной', 'Тяга в наклоне в Смите',
     'Вертикальная тяга в Смите',
     'Шраги рывковым хватом', 'Вертикальная тяга гантелей стоя',
     'Гудморнинг со штангой на прямых ногах',
     'Тяга к груди лёжа на скамье', 'Тяга верхнего блока прямыми руками',
     'Тяга в петлях',
     'Тяга Т-грифа с рукоятью', 'Тяга двух кеттлбелов',
     'Тяга верхнего блока обратным хватом',
     'Вертикальная тяга в кроссовере', 'Вертикальная тяга с резиной',
     'Тяга верхнего блока V-рукоятью',
     'Подтягивания V-рукоятью', 'Гиперэкстензия с медицинболом',
     'Подтягивания с отягощением',
     'Тяга верхнего блока широким хватом', 'Тяга верхнего блока за голову широким хватом',
     'Подтягивания за голову широким хватом'],

    # 2 Плечи (112)
    ['Поочерёдный жим в кроссовере', 'Поочерёдный подъём на дельты',
     'Поочерёдный жим кеттлбела', 'Антигравитационный жим', 'Жим Арнольда',
     'Разводка назад с резиной', 'Разведение резины в стороны',
     'Подъём штанги на наклонной (плечи)', 'Тяга штанги на заднюю дельту',
     'Жим штанги на плечи', 'Боевые канаты',
     'Обратные махи в наклоне с упором лбом',
     'Боковые махи из нижнего блока в наклоне', 'Жим Брэдфорда/Роки',
     'Внутреннее вращение плеча в кроссовере', 'Разводка на заднюю дельту в кроссовере',
     'Тяга каната на заднюю дельту',
     'Боковые махи в кроссовере сидя', 'Жим в кроссовере на плечи',
     '«Рулевое колесо»',
     'Цирковая гиря', 'Толчок', 'Взятие на грудь и жим', 'Распятие', 'Кубинский жим',
     'Толчок двух кеттлбелов', 'Жим двух кеттлбелов толчком', 'Рывок двух кеттлбелов',
     'Подъём гантелей на наклонной (плечи)',
     'Обратные махи лёжа одной рукой', 'Обратные махи лёжа',
     'Жим гантели одной рукой (плечи)', 'Вертикальная тяга гантели одной рукой',
     'Подъём гантелей', 'Подъём гантелей в плоскости лопатки',
     'Жим гантелей на плечи',
     'Внешнее вращение плеча', 'Внешнее вращение с резиной',
     'Внешнее вращение в кроссовере', 'Тяга к лицу',
     'Подъём вперёд в кроссовере', 'Подъём гантелей вперёд',
     'Подъём гантелей вперёд на наклонной', 'Подъём блина вперёд',
     'Подъём двух гантелей вперёд', 'Отжимания в стойке на руках',
     'Внутреннее вращение с резиной',
     'Железный крест', 'Жим с полуседом', 'Жим Арнольда с кеттлбелом',
     'Кеттлбел «пиратский корабль»',
     'Жим кеттлбела сидя', 'Жим кеттлбела «качели»', 'Траст с кеттлбелом',
     'Турецкий подъём с кеттлбелом (выпад)', 'Турецкий подъём с кеттлбелом (присед)',
     'Линейный жим с ленд-майном', 'Боковые махи с резиной',
     'Жим на плечи в рычажном тренажёре',
     'Жим бревна', 'Тяга нижнего блока к шее',
     'Боковые махи лёжа одной рукой', 'Обратные махи лёжа (2)',
     'Жим в тренажёре для плеч (военный)',
     'Боковые махи одной рукой на наклонной', 'Толчок кеттлбела одной рукой',
     'Жим-толчок кеттлбела одной рукой', 'Жим кеттлбела вбок одной рукой',
     'Параллельный жим кеттлбела одной рукой', 'Жим кеттлбела толчком одной рукой',
     'Рывок кеттлбела одной рукой', 'Разножка кеттлбела одной рукой',
     'Рывок-разножка кеттлбела одной рукой', 'Боковые махи одной рукой',
     'Силовые частичные повторения',
     'Жим толчком', 'Жим толчком за голову', 'Переброска с подставок',
     'Обратные махи', 'Обратные махи с внешней ротацией',
     'Обратные махи в тренажёре',
     'Жим штанги сидя (военный жим)', 'Обратные махи сидя в наклоне',
     'Жим в кроссовере сидя', 'Жим гантелей сидя', 'Боковые махи сидя',
     'Жим «качели»',
     'Жим на плечи с резиной',
     'Боковые махи', 'Боковые махи с переходом в подъём вперёд',
     'Подъём одной гантели', 'Линейный жим одной рукой',
     'Ходьба назад с санями над головой', 'Обратные махи с санями',
     'Подъём в Смите на наклонной (плечи)', 'Вертикальная тяга в Смите одной рукой',
     'Жим над головой в Смите',
     'Поочерёдный жим гантелей стоя', 'Жим штанги за голову стоя',
     'Жим Брэдфорда стоя', 'Жим гантелей стоя',
     'Подъём гантелей вперёд прямыми руками над головой',
     'Подъём штанги вперёд над головой', 'Подъём в нижнем блоке на дельты стоя',
     'Военный жим стоя', 'Жим гантели одной рукой ладонью внутрь стоя',
     'Жим гантелей стоя ладонями внутрь', 'Подъёмы на наклонной скамье (плечи)',
     'Взятие двух кеттлбелов на грудь', 'Толчок двух кеттлбелов (2)',
     'Военный жим двух кеттлбелов', 'Вертикальная тяга штанги'],

    # 3 Бицепс / Предплечья (73)
    ['Поочерёдный молоток', 'Поочерёдное сгибание на наклонной',
     'Сгибание рук со штангой', 'Сгибание со штангой лёжа на наклонной',
     'Взятие кеттлбела дном вверх',
     'Молоток в кроссовере (канат)', 'Сгибание в кроссовере на скамье Скотта',
     'Сгибание запястий в кроссовере',
     'Сгибание EZ-грифом узким хватом', 'Сгибание EZ-грифом узким хватом с резиной',
     'Сгибание стоя со штангой узким хватом', 'Концентрированное сгибание',
     'Молоток поперёк тела',
     'Сгибание протяжкой', 'Поочерёдное сгибание с гантелями',
     'Сгибание рук с гантелями',
     'Пронация гантели лёжа', 'Супинация гантели лёжа',
     'Сгибание с гантелями лёжа лицом вниз на наклонной', 'Сгибание с EZ-грифом',
     'Прогулка фермера', 'Сгибание пальцев',
     'Сгибание на сгибатели на наклонной', 'Молоток',
     'Сгибание в верхнем блоке',
     'Сгибание с гантелями на наклонной', 'Молоток на наклонной',
     'Сгибание на внутренний бицепс на наклонной',
     'Сгибание в кроссовере лёжа', 'Сгибание лёжа узким хватом в верхнем блоке',
     'Сгибание со штангой лёжа на высокой скамье', 'Сгибание с гантелями лёжа на спине',
     'Сгибание в тренажёре', 'Сгибание в тренажёре скамьи Скотта',
     'Сгибание одной рукой на скамье Скотта',
     'Сгибание в верхнем блоке над головой',
     'Сгибание запястий с гантелями ладонями вниз через скамью',
     'Сгибание запястий ладонями вниз через скамью',
     'Сгибание запястий со штангой ладонями вверх через скамью',
     'Сгибание запястий с гантелями ладонями вверх через скамью',
     'Удержание блина щипком',
     'Сгибание на скамье Скотта', 'Молоток на скамье Скотта',
     'Обратное сгибание со штангой',
     'Обратное сгибание на скамье Скотта', 'Обратное сгибание в кроссовере',
     'Обратное сгибание с блином',
     'Переноска рикши',
     'Концентрированное сгибание со штангой сидя узким хватом',
     'Сгибание с гантелями сидя', 'Сгибание на внутренний бицепс сидя',
     'Сгибание запястий с гантелями сидя ладонями вниз',
     'Сгибание запястий с гантелями сидя ладонями вверх',
     'Сгибание запястий одной рукой сидя ладонью вниз',
     'Сгибание запястий одной рукой сидя ладонью вверх',
     'Сгибание запястий со штангой сидя ладонями вверх',
     'Сгибание запястий со штангой сидя ладонями вниз',
     'Сгибание запястий двумя руками в нижнем блоке',
     'Паук-сгибание',
     'Сгибание в кроссовере стоя', 'Концентрированное сгибание стоя',
     'Обратное сгибание с гантелями стоя', 'Сгибание на внутренний бицепс стоя',
     'Удержание блина стоя', 'Сгибание одной рукой в кроссовере стоя',
     'Сгибание одной рукой с гантелью через наклонную скамью',
     'Сгибание запястий со штангой за спиной',
     'Сгибание двумя руками на скамье Скотта',
     'Сгибание со штангой широким хватом стоя',
     'Ролик для запястий', 'Вращение запястий с грифом',
     'Сгибание Зоттмана', 'Сгибание Зоттмана на скамье Скотта'],

    # 4 Трицепс (67)
    ['Французский жим с резиной', 'Дипсы на скамье',
     'Жим лёжа (пауэрлифтинг)', 'Жим лёжа с цепями',
     'Жим с доской', 'Жим трицепса весом тела', 'Подъём тела',
     'Разгибание в кроссовере на наклонной',
     'Разгибание в кроссовере лёжа', 'Разгибание одной руки в кроссовере',
     'Разгибание над головой с канатом в кроссовере',
     'Разгибание с ручкой и цепями',
     'Жим штанги узким хватом', 'Жим гантелей узким хватом',
     'Жим EZ-грифа узким хватом',
     'Отжимания с опорой на гантель узким хватом',
     'Жим узким хватом на обратном наклоне в французский',
     'Разгибание гантели на обратном наклоне',
     'Разгибание EZ-грифа на обратном наклоне',
     'Тренажёр для дипсов', 'Дипсы (трицепс)',
     'Жим гантелей лёжа на полу',
     'Разгибание гантели одной рукой',
     'Разгибание гантели пронированным хватом',
     'Французский жим с EZ-грифом', 'Жим лёжа на полу',
     'Жим лёжа на полу с цепями',
     'Разгибание штанги на наклонной', 'Отжимания узким хватом на наклонной',
     'JM-жим',
     'Разгибание в кроссовере на коленях', 'Разгибание в нижнем блоке',
     'Французский жим узким хватом лёжа за голову',
     'Жим узким хватом лёжа к подбородку',
     'Разгибание гантели лёжа', 'Жим на трицепс лёжа',
     'Разгибание в тренажёре для трицепса', 'Жим одной рукой на полу',
     'Разгибание гантели пронацией одной рукой',
     'Разгибание гантели супинацией одной рукой',
     'Дипсы на параллельных брусьях',
     'Жим с упоров', 'Отжимания — узкая позиция трицепса',
     'Жим с резиной снизу',
     'Разгибание обратным хватом в кроссовере', 'Жим лёжа обратным хватом',
     'Дипсы на кольцах',
     'Разгибание гантели одной рукой в наклоне сидя',
     'Разгибание гантелей двумя руками в наклоне сидя',
     'Жим на трицепс сидя',
     'Разгибание трицепса с санями над головой',
     'Жим узким хватом в Смите',
     'Скоростное разгибание над головой с резиной',
     'Разгибание гантели одной рукой в наклоне стоя',
     'Разгибание гантелей двумя руками в наклоне стоя',
     'Разгибание гантели стоя',
     'Разгибание одной рукой в нижнем блоке стоя',
     'Разгибание гантели одной рукой стоя',
     'Разгибание штанги над головой стоя', 'Разгибание с полотенцем стоя',
     'Жим Тейт', 'Отдача с гантелью (кикбэк)',
     'Разгибание над головой с канатом',
     'Разгибание в кроссовере', 'Разгибание в кроссовере с канатом',
     'Разгибание в кроссовере с V-рукоятью',
     'Дипсы на скамье с отягощением'],

    # 5 Пресс (81)
    ['Скручивание 3/4', 'Пресс-машина', 'Ролик для пресса',
     'Ветряная мельница с кеттлбелом (продвинутый)',
     'Велосипед в воздухе', 'Поочерёдное касание пяток',
     'Ролик для пресса со штангой', 'Ролик для пресса со штангой на коленях',
     'Ролик для пресса со штангой со скамьи', 'Боковые наклоны со штангой',
     'Жим в наклон', 'Подъём таза с согнутыми коленями',
     'Скручивание на Bosu с боковыми наклонами в кроссовере',
     'Подъём снизу', 'Подъём таза',
     'Скручивание в кроссовере', 'Бросок дзюдо в кроссовере',
     'Обратное скручивание в кроссовере', 'Русский твист в кроссовере',
     'Скручивание в кроссовере сидя', 'Кокон',
     'Скручивание к противоположному колену', 'Скручивание руки над головой',
     'Скручивание ноги на мяче',
     'Скручивания', 'Мёртвый жук', 'Скручивание на наклонной',
     'Косое скручивание на наклонной', 'Обратное скручивание на наклонной',
     'Ветряная мельница с двумя кеттлбелами',
     'Боковые наклоны с гантелью', 'Локоть к колену',
     'Скручивание на мяче', 'Подтягивание ног на мяче',
     'Подтягивание ног лёжа на скамье', 'Подъём ног лёжа на скамье',
     'Скручивания «лягушка»', 'Скручивание горилла',
     'Подъём ног в висе', 'Подъём в упор в висе',
     'Складной нож', 'Скручивание Янды',
     'Восьмёрка с кеттлбелом', 'Перекидывание кеттлбела между ногами',
     'Ветряная мельница с кеттлбелом',
     'Подъём коленей/таза в упоре на брусьях',
     'Скручивание на коленях в кроссовере с косыми поворотами',
     'Ленд-майн 180°',
     'Подтягивание ног', 'Косые скручивания', 'Косые скручивания на полу',
     'Боковые наклоны в верхнем блоке одной рукой',
     'Удар медицинболом одной рукой',
     'Скручивание Отиса',
     'Жим Паллоф', 'Жим Паллоф с поворотом', 'Планка', 'Скручивание с блином',
     'Скручивание с жимом', 'Обратное скручивание', 'Скручивание с канатом',
     'Русский твист',
     'Поворот с гантелями сидя', 'Подтягивание ног сидя на скамье',
     'Подтягивание коленей сидя',
     'Боковая планка', 'Боковой складной нож', 'Подъём туловища',
     'Подъём таза в Смите',
     'Заклинатель', 'Паучье ползание',
     'Подъём в кроссовере стоя', 'Дровосек в кроссовере стоя',
     'Скручивание с канатом стоя', 'Выпад в петлях',
     'Обратное скручивание в петлях',
     'Скручивание в группировке', 'Боковые наклоны с медицинболом',
     'Скручивания с отягощением', 'Подъём туловища с отягощением и резиной',
     'Спринты'],

    # 6 Квадрицепс (93)
    ['Тяга назад (сани)', 'Полные приседания со штангой',
     'Гакк-приседания со штангой', 'Выпады со штангой',
     'Боковые приседания со штангой', 'Приседания со штангой',
     'Приседания со штангой на скамью', 'Зашагивания со штангой',
     'Выпады в ходьбе со штангой', 'Тяга саней в медвежьей ходьбе',
     'Приседания без отягощения', 'Выпады в ходьбе без отягощения',
     'Приседания на ящик',
     'Приседания на ящик с резиной', 'Приседания на ящик с цепями',
     'Становая тяга в кроссовере', 'Сведение бёдер в кроссовере',
     'Становая тяга с автомобилем', 'Присед на стул', 'Тяга в подрыве',
     'Взятие на грудь с подставок', 'Колесо Конана',
     'Выпады с гантелями', 'Выпады назад с гантелями',
     'Приседания с гантелями', 'Приседания с гантелями на скамью',
     'Зашагивания с гантелями',
     'Выпады с задней ногой на возвышении', 'Приседания Франкенштейна',
     'Прыжок из приседа без отягощения',
     'Фронтальные приседания со штангой', 'Фронтальные приседания со штангой на скамью',
     'Фронтальные приседания (хват рывка)', 'Фронтальные приседания с двумя кеттлбелами',
     'Присед с гирей (гоблет)',
     'Гакк-приседания', 'Взятие на грудь с виса', 'Взятие на грудь с виса ниже колен',
     'Равновесие в рывке', 'Сгибание бедра с резиной',
     'Приседания Джефферсона',
     'Присед в рывке', 'Пистолет с кеттлбелом',
     'Разгибание ног в тренажёре', 'Жим ногами',
     'Становая тяга в рычажном тренажёре', 'Спринт с выпадами',
     'Приседания в тренажёре лёжа',
     'Гакк-приседания узкой стойкой', 'Жим ногами узкой стойкой',
     'Приседания узкой стойкой',
     'Олимпийские приседания', 'Приседания на одной ноге со штангой',
     'Приседания с кеттлбелом над головой одной рукой',
     'Становая тяга сбоку одной рукой', 'Приседания со штангой над головой',
     'Плие с гантелью', 'Силовой толчок',
     'Силовой рывок с подставок',
     'Приседания на ящик с резиной снизу', 'Силовые приседания с резиной снизу',
     'Становая тяга с рикшей', 'Подъём мешка с песком',
     'Приседания на одной ноге на высокий ящик',
     'Разгибание одной ноги в тренажёре',
     'Тяга саней в шлейке', 'Толкание саней',
     'Жим ногами в Смите', 'Пистолет в Смите', 'Приседания в Смите',
     'Болгарский сплит-присед в Смите',
     'Рывок', 'Равновесие в рывке (баланс)', 'Рывок с подставок',
     'Скоростные приседания на ящик', 'Скоростные приседания',
     'Взятие на грудь в разножку', 'Толчок в разножку',
     'Сплит-присед с гантелями', 'Толчок в глубокий присед',
     'Приседания с резиной', 'Приседания с цепями',
     'Приседания с перемещением блинов', 'Приседания с резиной (2)',
     'Сплит-присед в петлях', 'Переворот покрышки',
     'Становая тяга с трэп-грифом',
     'Прыжок из приседа с отягощением', 'Сисси-присед с отягощением',
     'Приседания с отягощением', 'Приседания широкой стойкой со штангой',
     'Ходьба с ярмом', 'Приседания Зерчера'],

    # 7 Бицепс бедра (50)
    ['Поочерёдное взятие на грудь с виса', 'Сгибание ног на мяче',
     'Гудморнинг с резиной', 'Гудморнинг с резиной (протяжка)',
     'Взятие на грудь',
     'Становая тяга в стиле взятия',
     'Поочерёдное взятие двух кеттлбелов с виса', 'Взятие на грудь с гантелями',
     'Подъём на GHD на полу', 'Подъём на GHD',
     'Гудморнинг', 'Гудморнинг с упоров',
     'Рывок с виса', 'Рывок с виса ниже колен',
     'Гудморнинг с подвешенной штангой',
     'Мёртвое взятие кеттлбела', 'Взятие кеттлбела с виса',
     'Становая тяга на одной ноге с кеттлбелом',
     'Выпад с передачей', 'Сгибание ног лёжа',
     'Мышечный рывок', 'Натуральный подъём на GHD',
     'Взятие кеттлбела одной рукой', 'Махи кеттлбелом одной рукой',
     'Взятие кеттлбела открытой ладонью одной рукой',
     'Взятие кеттлбела открытой ладонью',
     'Скольжение на платформе (бицепс бедра)',
     'Силовое взятие на грудь', 'Силовое взятие с подставок',
     'Силовой рывок', 'Силовая лестница',
     'Ручное сопротивление для бицепса бедра лёжа',
     'Становая тяга сумо с резиной снизу', 'Обратная гиперэкстензия',
     'Румынская тяга', 'Румынская тяга с дефицита',
     'Сгибание ног с резиной сидя', 'Сгибание ног сидя',
     'Силовое взятие с виса в Смите',
     'Становая тяга на прямых ногах в Смите',
     'Становая тяга рывковым хватом', 'Тяга в рывке',
     'Рывок в разножку', 'Сгибание ноги стоя',
     'Становая тяга со штангой на прямых ногах',
     'Становая тяга с гантелями на прямых ногах',
     'Становая тяга сумо', 'Становая тяга сумо с резиной',
     'Становая тяга сумо с цепями',
     'Тяга на прямых ногах широкой стойкой'],

    # 8 Ягодицы / Отводящие / Приводящие (20)
    ['Сведение бёдер с резиной', 'Ягодичный мостик со штангой',
     'Тяга бёдрами со штангой', 'Подъём ягодиц (мостик)',
     'Баланс лицом вниз', 'Ножницы',
     'Мах ногой назад', 'Разгибание бедра с резиной', 'Подъём таза с резиной',
     'Прыжок из приседа на коленях', 'Присед на коленях',
     'Подъём ноги', 'Ходьба монстра',
     'Мах ногой назад в кроссовере', 'Ягодичный мостик на мяче',
     'Протяжка', 'Ягодичный мостик на одной ноге',
     'Зашагивание с подъёмом колена',
     'Отведение бедра (тренажёр)', 'Сведение бедра (тренажёр)'],

    # 9 Икры (15)
    ['Баланс-борд', 'Подъём на носки сидя со штангой',
     'Жим икрами', 'Подъём на носки в жиме ногами',
     'Подъём на носки на гантели',
     'Подъём на носки с резиной', 'Ослиные подъёмы',
     'Подъём на носке одной ноги с гантелью сидя',
     'Подъём на носки стоя с покачиванием',
     'Подъём на носки сидя', 'Подъём на носки в Смите',
     'Обратный подъём на носки в Смите',
     'Подъём на носки со штангой стоя', 'Подъём на носки стоя',
     'Подъём на носки с гантелью стоя'],

    # 10 Кардио / Плиометрика (75)
    ['Поочерёдный диагональный прыжок', 'Бросок медицинбола назад',
     'Прыжок через скамью', 'Спринт на скамье',
     'Езда на велосипеде', 'Велотренажёр',
     'Прыжок на ящик (серийный)', 'Прыжки через ящик',
     'Карьока (быстрый шаг)', 'Перехват и бросок над головой',
     'Толчок от груди (серийный)', 'Толчок от груди (одиночный)',
     'Толчок от груди из трёхточечной стойки', 'Толчок от груди с ускорением',
     'Прыжок из глубины', 'Удар пятками двумя ногами',
     'Прыжковое отжимание', 'Прыжок на ящик с гантелями сидя',
     'Эллиптический тренажёр', 'Быстрое скакалочное',
     'Прыжок на ящик вперёд', 'Прыжки через конус вперёд',
     'Удар по груше', 'Прыжки через барьер',
     'Отжимания с глубиной на наклонной', 'Изометрическое сжатие грудных',
     'Лёгкий бег на дорожке', 'Прыжок с подтягиванием колен',
     'Работа руками на коленях',
     'Боковой прыжок', 'Боковой прыжок на ящик', 'Боковые прыжки через конус',
     'Линейная техника старта (3 части)', 'Линейное ускорение у стены',
     'Линейный прыжок из глубины',
     'Передача медицинбола от груди', 'Полный поворот с медицинболом',
     'Бросок медицинбола снизу', 'Скалолаз',
     'Серия «коготь»', 'Бросок об пол над головой',
     'Плиометрические отжимания', 'Спринт с Prowler',
     'Быстрый прыжок', 'Велотренажёр лёжа',
     'Толчок назад из стойки', 'Прыжок ракета',
     'Прыжки со скакалкой', 'Гребной тренажёр',
     'Бег на дорожке', 'Прыжок ножницы',
     'Боковой прыжок-спринт', 'Боковой прыжок в длину',
     'Боковое перемещение через ящик', 'Удар пяткой одной ногой',
     'Отталкивание одной ногой', 'Спринт с конусом',
     'Прогрессивные прыжки на одной ноге', 'Боковой прыжок на одной ноге',
     'Шаговый прыжок на одной ноге', 'Катание на коньках',
     'Удары кувалдой', 'Прыжок в выпаде', 'Степпер',
     'Прыжок в длину с места', 'Бросок двумя руками над головой стоя',
     'Прыжок звезда', 'Тренажёр-лестница',
     'Шаговый прыжок с перекрёстом', 'Бросок от груди лёжа на спине',
     'Бросок над головой одной рукой лёжа', 'Бросок двумя руками над головой лёжа',
     'Трейл-бег/ходьба', 'Вертикальный свинг', 'Ходьба на дорожке'],
]


def get_catalog(lang: str) -> list[list[str]]:
    """Return exercise list for given language code. Falls back to English."""
    return _RU if lang == "ru" else _EN
